<template>
  <button
    class="
      cursor-pointer
      w-8
      h-8
      p-2
      rounded-md
      flex
      items-center
      justify-center
      bg-gradient-to-r
      from-amber-500
      to-yellow-400
      hover:from-amber-600
      hover:to-yellow-500
      active:scale-95
      active:from-amber-700
      active:to-yellow-600
      transition-all
      duration-200
      shadow-md
      hover:shadow-lg
      dark:shadow-amber-900/30
      dark:hover:shadow-amber-900/40
      focus:outline-none
      focus:ring-2
      focus:ring-amber-300
      dark:focus:ring-amber-500
      text-white
      disabled:opacity-50
      disabled:cursor-not-allowed
      disabled:shadow-none
      disabled:hover:from-amber-500
      disabled:hover:to-yellow-400
      disabled:active:from-amber-500
      disabled:active:to-yellow-400
    "
    type="button"
  >
    <slot />
  </button>
</template>
